export type DataTableConfig = typeof dataTableConfig

export const dataTableConfig = {
  textOperators: [
    { label: '含む', value: 'iLike' as const },
    { label: '含まない', value: 'notILike' as const },
    { label: '等しい', value: 'eq' as const },
    { label: '等しくない', value: 'ne' as const },
    { label: '空', value: 'isEmpty' as const },
    { label: '空でない', value: 'isNotEmpty' as const },
  ],
  numericOperators: [
    { label: '等しい', value: 'eq' as const },
    { label: '等しくない', value: 'ne' as const },
    { label: 'より小さい', value: 'lt' as const },
    { label: '以下', value: 'lte' as const },
    { label: 'より大きい', value: 'gt' as const },
    { label: '以上', value: 'gte' as const },
    { label: '範囲内', value: 'isBetween' as const },
    { label: '空', value: 'isEmpty' as const },
    { label: '空でない', value: 'isNotEmpty' as const },
  ],
  dateOperators: [
    { label: '等しい', value: 'eq' as const },
    { label: '等しくない', value: 'ne' as const },
    { label: 'より前', value: 'lt' as const },
    { label: 'より後', value: 'gt' as const },
    { label: '以前', value: 'lte' as const },
    { label: '以降', value: 'gte' as const },
    { label: '範囲内', value: 'isBetween' as const },
    { label: '今日基準', value: 'isRelativeToToday' as const },
    { label: '空', value: 'isEmpty' as const },
    { label: '空でない', value: 'isNotEmpty' as const },
  ],
  selectOperators: [
    { label: '等しい', value: 'eq' as const },
    { label: '等しくない', value: 'ne' as const },
    { label: '空', value: 'isEmpty' as const },
    { label: '空でない', value: 'isNotEmpty' as const },
  ],
  multiSelectOperators: [
    { label: 'いずれかを含む', value: 'inArray' as const },
    { label: 'いずれも含まない', value: 'notInArray' as const },
    { label: '空', value: 'isEmpty' as const },
    { label: '空でない', value: 'isNotEmpty' as const },
  ],
  booleanOperators: [
    { label: '等しい', value: 'eq' as const },
    { label: '等しくない', value: 'ne' as const },
  ],
  sortOrders: [
    { label: '昇順', value: 'asc' as const },
    { label: '降順', value: 'desc' as const },
  ],
  filterVariants: [
    'text',
    'number',
    'range',
    'date',
    'dateRange',
    'boolean',
    'select',
    'multiSelect',
  ] as const,
  operators: [
    'iLike',
    'notILike',
    'eq',
    'ne',
    'inArray',
    'notInArray',
    'isEmpty',
    'isNotEmpty',
    'lt',
    'lte',
    'gt',
    'gte',
    'isBetween',
    'isRelativeToToday',
  ] as const,
  joinOperators: ['and', 'or'] as const,
}
